name: Deploy Image to GHCR

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mgdigital
          password: ${{secrets.GHCR_TOKEN}}
      - name: "Build and push"
        run: |
          docker build . --tag ghcr.io/mgdigital/rarbg-selfhosted:${GITHUB_REF#refs/tags/} --tag ghcr.io/mgdigital/rarbg-selfhosted:latest
          docker push --all-tags ghcr.io/mgdigital/rarbg-selfhosted
